### ISSUE TITLE
Polylint Sublimelinter plugin?

### ISSUE THREAD

**Issue by nomego** [PolymerLabs/polylint#22]
It seems like the Polymer team uses Sublime Text, would you consider creating a plugin for SublimeLinter (http://www.sublimelinter.com/en/latest/) for Polylint?

It seems pretty straight-forward, considering a sample plugin such as SublimeLinter-contrib-jslint (https://github.com/devdoc/SublimeLinter-jslint/blob/master/linter.py)

**Comment by abdonrd** [comment]
And another plugin for Atom! :)

**Comment by addyosmani** [comment]
I considered writing a SublimeLinter plugin on top of Polylint but didn't have a chance to before the summit. Unless @garlicnation had this on his roadmap, I'm sure we'd super-appreciate help putting one together.

**Comment by BLamy** [comment]
+1 for atom. I'd write one myself but I can't even seem to get polylint to run at all.

**Comment by addyosmani** [comment]
I'd say it would be interesting to start prototyping this if anyone wanted to take it on.

**Comment by nomego** [comment]
Ok so I sent two PRs to hydrolysis and this polylint project.
If both are merged, there's a working prototype SublimeLinter plugin at https://github.com/nomego/SublimeLinter-contrib-polylint

I will not submit this plugin for inclusion in SublimeLinter until above PRs are merged.

**Comment by addyosmani** [comment]
@nomego Awesome! https://github.com/Polymer/hydrolysis/pull/168 was just landed. @garlicnation when you get a chance, would be rad to get another review on https://github.com/PolymerLabs/polylint/pull/32.

**Comment by nomego** [comment]
SublimeLinter-contrib-polylint 1.0.0 should be possible to install through Package Control.
