### ISSUE TITLE
Behavior Polymer.Templatizer not found!

### ISSUE THREAD

**Issue by davidmaxwaterman** [PolymerLabs/polylint#24]
I'm trying to run polylint on this file :

<https://github.com/01org/nlpljs/blob/mw-polymer-1.0-upgrade/example-app/app/content_push/cp-aggregator.html>

I keep getting this error :

```
[app]$ polylint content_push/cp-aggregator.html 
Behavior Polymer.Templatizer not found!
Behavior Polymer.Templatizer not found!
Behavior Polymer.Templatizer not found!
[app]$ 
```

Can you tell me how to use polylint on this file?

In the polylint readme, the example shows using it on an index.html file, but this app doesn't have one since the elements are added using a content script (in a chrome extension).

Thanks for pointers.

**Comment by Westbrook** [comment]
I see the same response no matter what way I enter the commands:

```
polylint index.html
polylint --input index.html
polylint --root project/ --input index.html
```

I was hoping it was just missing the `--input`, but no matter how I include the commands it comes back like:

```
Behavior Polymer.Templatizer not found!
Behavior Polymer.Templatizer not found!
Behavior Polymer.Templatizer not found!
```

What are we missing?

**Comment by garlicnation** [comment]
Fixed with https://github.com/Polymer/hydrolysis/pull/167

**Comment by davidmaxwaterman** [comment]
lgtm
