### ISSUE TITLE
Linting reuseable elements (seed-element)

### ISSUE THREAD

**Issue by Scarygami** [PolymerLabs/polylint#28]
Because of the way reuseable elements are structured `polylint` doesn't find the dependencies.

Imports from `../{{dependency}}` would have to be taken from `./bower_components/{{dependency}}` instead.

`polyserve` solved this issue when testing/demoing elements, it would be sad to have to go back to restructuring project folders and using `.bowerrc` to be able to lint custom elements.

**Comment by garlicnation** [comment]
Polylint does this by default. Did you test it and find that it wasn't searching bower_components?
https://github.com/PolymerLabs/polylint/blob/master/polylint.js#L31

**Comment by garlicnation** [comment]
This regressed in 2.0 and has been fixed in 2.3
