### ISSUE TITLE
Remove dependency on node-gyp

### ISSUE THREAD

**Issue by dsschnau** [PolymerLabs/polylint#33]
This is the error I get trying to install polylint on my windows machine.

![image](https://cloud.githubusercontent.com/assets/1373329/10210014/d4ce06d0-67af-11e5-8c51-47d4ff79d471.png)

Digging into it lead me to [this issue with nodejs on windows](https://github.com/nodejs/node-v0.x-archive/issues/8005)

What is the reason for this dependency? Tools like [eslint](http://eslint.org/) work just fine on my windows machine.

**Comment by mashimom** [comment]
Similar error on LInux with node v4.1.0

**Comment by dsschnau** [comment]
Another part of why this confuses me - nody-gyp doesn't show up in polylint's dependency tree.

[npm-remote-ls](https://github.com/npm/npm-remote-ls) lists the dependency tree of a given npm module, and it doesn't show up.

![image](https://cloud.githubusercontent.com/assets/1373329/10220960/14c2e2f6-6819-11e5-9ecc-537d860a84a6.png)

**Comment by ebidel** [comment]
```npm -v; node -v
2.5.1
v0.12.7
```

<img width="857" alt="screen shot 2015-10-02 at 2 25 41 pm" src="https://cloud.githubusercontent.com/assets/238208/10258209/87a8ca3a-6911-11e5-83fa-d797814914bc.png">

**Comment by garlicnation** [comment]
@justinfagnani `polymer-expression` was causing this issue. I'm not using it presently so I just removed it, but I wonder if you know what the root cause was.

**Comment by garlicnation** [comment]
@dsschnau Fixed w/ the latest release.

**Comment by dsschnau** [comment]
Awesome, thank you!
