### ISSUE TITLE
Atom package Polylint

### ISSUE THREAD

**Issue by abdonrd** [PolymerLabs/polylint#51]
Any plans to create Atom package Polylint? :smiley:

**Comment by garlicnation** [comment]
There are! I'll update this repo when we have more details.

**Comment by abdonrd** [comment]
Yeah! Thanks @garlicnation!

**Comment by abdonrd** [comment]
Any news about the Atom package, @garlicnation? :blush:

**Comment by vaadin-marcus** [comment]
@abdonrd: there's now a `polymer-atom` package for atom
