### ISSUE TITLE
False positive on "property not found"

### ISSUE THREAD

**Issue by kjlubick** [PolymerLabs/polylint#64]
Using the latest polylint (2.7), I now seem to get a false positive for the following element:
https://gist.github.com/kjlubick/001cf6003c20a19d36d4#file-status-html

`Property  lastcommit not found in 'properties' for element 'fuzzer-status-sk'`

At first, I had lastCommit and so I thought it was a camel-case problem, but it doesn't appear to be so.

**Comment by kjlubick** [comment]
I figured out what was causing the stir, but it might still be a bug.

`{{ lastcommit.shortHash }}` was problematic while `{{lastcommit.shortHash}}` was fine.  Somehow, polylint thought my variable name was ' lastcommit' with a leading space.

**Comment by kjlubick** [comment]
What was also confusing about this was the column number pointed to the '>' of the anchor tag and not the actual problem

**Comment by tjsavage** [comment]
Just ran into this as well
