### ISSUE TITLE
polylint should whitespace native properties

### ISSUE THREAD

**Issue by notwaldorf** [PolymerLabs/polylint#90]
For example, it is convinced `paper-input` doesn't have a `tabindex`, which is not true (everyone and their cat has a `tabindex`)

Originally filed as https://github.com/PolymerElements/paper-input/issues/288

**Comment by sandro-k** [comment]
+1 currently my build is failing with polylint complaining about  `tabindex` aka `tabIndex`

**Comment by cdata** [comment]
Same issue, this is more topical now that we are running Polylint on our PR builds. A fix for this would be very appreciated!

https://travis-ci.org/PolymerElements/paper-slider/builds/101732850

**Comment by ronnyroeller** [comment]
+1

**Comment by ronnyroeller** [comment]
Is there any known workaround for this issue?
